# этап сборки (build stage)
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend .
RUN npm run build

# этап production (production-stage)
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/nginx.conf /etc/nginx/nginx.conf
COPY --from=build-stage /app/dist/spa /dist/
COPY .ssl /etc/ssl
EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
