version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
      no_cache: true
    volumes:
      - ./frontend:/app
    ports:
      - "9000:9000"
      - "9010:9010"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - "./:/app/"
    depends_on:
      - postgres
      - mongo
  
  postgres:
    image: postgres:14
    env_file: .env
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
    ports:
     - "5432:5432"
  
  mongo:
    image: mongo
    volumes:
      - ./.mongo_data:/data/db
    ports:
      - "27017:27017"
