##########################
FROM golang:1.21-alpine3.18 AS builder

WORKDIR /app
COPY . .
RUN go mod download && \
    CGO_ENABLED=0 GOOS=linux go build -a -o ./main ./main.go


###########################
FROM scratch
COPY --from=builder ["/app/main", "/main"]
COPY --from=builder ["/app/.env", "/.env"]
COPY .ssl/certificate_ca.crt /etc/ssl/certs/certificate_ca.crt
EXPOSE 3000
CMD [ "/main" ]
