// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/v1/sebastian.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SebastianClient is the client API for Sebastian service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SebastianClient interface {
	// Sends a greeting
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
}

type sebastianClient struct {
	cc grpc.ClientConnInterface
}

func NewSebastianClient(cc grpc.ClientConnInterface) SebastianClient {
	return &sebastianClient{cc}
}

func (c *sebastianClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/sebastian.Sebastian/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SebastianServer is the server API for Sebastian service.
// All implementations must embed UnimplementedSebastianServer
// for forward compatibility
type SebastianServer interface {
	// Sends a greeting
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	mustEmbedUnimplementedSebastianServer()
}

// UnimplementedSebastianServer must be embedded to have forward compatible implementations.
type UnimplementedSebastianServer struct {
}

func (UnimplementedSebastianServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedSebastianServer) mustEmbedUnimplementedSebastianServer() {}

// UnsafeSebastianServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SebastianServer will
// result in compilation errors.
type UnsafeSebastianServer interface {
	mustEmbedUnimplementedSebastianServer()
}

func RegisterSebastianServer(s grpc.ServiceRegistrar, srv SebastianServer) {
	s.RegisterService(&Sebastian_ServiceDesc, srv)
}

func _Sebastian_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SebastianServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sebastian.Sebastian/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SebastianServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sebastian_ServiceDesc is the grpc.ServiceDesc for Sebastian service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sebastian_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sebastian.Sebastian",
	HandlerType: (*SebastianServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _Sebastian_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/sebastian.proto",
}
