name: Deploy Vue App with Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: cd frontend && npm install

      - name: Build
        run: cd frontend && npm run build

      # - name: Deploy to Server
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     rm: true
      #     source: "dist/*"
      #     target: "/var/www/html"

      # - name: Restart Nginx
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_HOST }}
      #     username: ${{ secrets.SERVER_USER }}
      #     key: ${{ secrets.SERVER_SSH_KEY }}
      #     script: |
      #       sudo systemctl reload nginx