name: Deploy Vue App with Nginx

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: cd frontend && npm install

      - name: Build
        run: cd frontend && npm run build

      - name: Remove
        run: cd /var/www/html && rm -rf *

      - name: Move dist
        run: mv frontend/dist/spa/* /var/www/html/

      - name: Reload nginx
        run: sudo systemctl reload nginx
